hw: 6
class_path: assets/elevator2_unofficial.jar
stu_id: 23066666 # 学号
stu_pwd: 'password' # 密码
jar_base_dir: jar
hacker:
  std_jar_name: d42012e7546248594c26a7d9e865429c88e6ea8e.jar # 标准输出jar包的文件名
  checker_name: checker.py             # checker脚本的文件名
  generator_name: gen.py               # generator脚本的文件名
  hack_dir: hack                       # hack数据存放目录 (用于存放stdin/stdout)
  num_generate: 10                     # 一次生成多少个随机数据点
  debug: True                          # False 时打开浏览器的 Headless 模式
  courseid: 62                         # 课程ID