hw: 14
assets_dir: assets
class_path: library2.jar
stu_id: 23066666 # 学号
stu_pwd: 'password' # 密码
jar_base_dir: jar
logs_dir: logs
tmp_dir: tmp
hacker:
  std_jar_name: hw_7.jar               # 标准输出jar包的文件名
  checker_name: checker.py             # checker脚本的文件名
  generator_name: gen.py               # generator脚本的文件名
  hack_dir: hack                       # hack数据存放目录 (用于存放stdin/stdout)
  num_generate: 10                     # 一次生成多少个随机数据点
  debug: False
  courseid: 62                         # 课程ID
update:
  log_prefix: errors
  log_suffix: .log
  target_line_prefix: 'Input Data File Path:'
test:
  min_wall_time_limit: 15.0                 # (seconds) Minimum floor for any wall time limit
  base_wall_time_per_cycle: 2.5             # (seconds) Estimated time per cycle in driver.py
  base_fixed_overhead_time: 5.0             # (seconds) Estimated fixed overhead for driver
  default_estimated_wall_time: 50.0         # (seconds) Fallback if --max_cycles not in preset
  cycle_cpu_timeout: 0.2                    # (seconds) wait time for driver to wait every cycle
  gap: 0.5                                  # (seconds) wait time after every Running Round
  parallel: 8
  debug: False
  cleanup: True