hw: 9
assets_dir: assets
class_path: hw9_official.jar
stu_id: 23066666 # 学号
stu_pwd: 'password' # 密码
jar_base_dir: jar
logs_dir: logs
tmp_dir: tmp
hacker:
  std_jar_name: hw_7.jar               # 标准输出jar包的文件名
  checker_name: checker.py             # checker脚本的文件名
  generator_name: gen.py               # generator脚本的文件名
  hack_dir: hack                       # hack数据存放目录 (用于存放stdin/stdout)
  num_generate: 10                     # 一次生成多少个随机数据点
  debug: False
  courseid: 62                         # 课程ID
update:
  log_prefix: errors
  log_suffix: .log
  target_line_prefix: 'Input Data File Path:'
test:
  hce: False
  parallel: 16
  debug: False
  cleanup: True